dev/iheroes/config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/heros')
  devise_for :users
  resources :heros
  get 'threats', to: 'threats#index'
  post 'threats/create', to: 'threats#create'

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

dev/iheroes/app/models/hero.rb
class Hero < ApplicationRecord
  # validations
  validates :name, presence: true
  validates :rank, presence: true

  # associations
  has_many :threats

  # scopes
  scope :a_heros, -> do
    where(rank: 'A')
  end

  scope :b_heros, -> do
    where(rank: 'B')
  end

  scope :c_heros, -> do
    where(rank: 'C')
  end

  scope :s_heros, -> do
    where(rank: 'S')
  end
end

dev/iheroes/app/controllers/heros_controller.rb
class HerosController < ApplicationController
  before_action :set_hero, only: %i[show edit update destroy]

  def index
    @heros = Hero.all
  end

  def show; end

  def new
    @hero = Hero.new
  end

  def create
    @hero = Hero.new(heros_params)

    respond_to do |format|
      if @hero.save
        format.html { redirect_to @hero, notice: 'Hero was successfully created.' }
        format.json { render json: @hero, status: :created, location: @hero }
      else
        format.html { render action: "new" }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @hero.update_attributes(heros_params)
        format.html { redirect_to @hero, notice: 'Hero was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @hero.destroy
  end

  private

  def heros_params
    params.require(:hero).permit(:name, :rank)
  end

  def set_hero
    @hero = Hero.find(params[:id])
  end
end

dev/iheroes/app/helpers/heros_helper.rb
module HerosHelper
end

dev/iheroes/app/views/heros/_form.html.erb
<div class="container text-center col-4">
  <h4><%= action_name == 'edit' ? 'Edit Hero' : 'Create Hero' %></h4>
  <%= form_for(@hero) do |f| %>
    <% if @hero.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@hero.errors.count, "error") %> prohibited this hero from being saved:</h2>

        <ul>
        <% @hero.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="fields">
      <%= f.label :name, class: 'form-label' %><br />
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :rank, class: 'form-label' %><br />
      <%= f.select(:rank, options_for_select(["S", "A", "B", "C"]), { prompt: "Selecione" }, { class: 'custom-select'}) %>
    </div>
    <div class="actions mt-2">
      <%= f.submit "Send", class: 'btn btn-primary' %>
      <% if action_name == 'edit' %>
        <%= link_to 'Voltar', hero_path(@hero), class: 'btn btn-outline-primary' %>
      <% else %>
        <%= link_to 'Voltar', heros_path, class: 'btn btn-outline-primary' %>
      <% end %>
    </div>

  <% end %>
</div>

dev/iheroes/app/views/heros/edit.html.erb
<%= render 'form' %>

dev/iheroes/app/views/heros/index.html.erb
<div class="container text-center">
  <h1>Listing Heros</h1>
  <%= link_to 'New hero', new_hero_path, class: 'btn btn-primary' %>
  <%= link_to 'Threats', threats_path, class: 'btn btn-outline-primary' %>
  <div class="row mt-2">
  <% @heros.each do |hero| %>
    <div class="card col-4 mt-2">
        <div class="card-header">
          <div>
            <strong><%= hero.name %></strong>
          </div>
          <div>
            Rank: <%= hero.rank %>
          </div>
        </div>
      <div class="card-body card-hero">
        <%= link_to 'Show', hero, class: 'btn btn-primary' %>
        <%= link_to 'Edit', edit_hero_path(hero), class: 'btn btn-outline-primary' %>
        <%= link_to 'Destroy', hero, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
      </div>
    </div>
  <% end %>
  </div>
</div>

dev/iheroes/app/views/heros/new.html.erb
<%= render 'form' %>

dev/iheroes/app/views/heros/show.html.erb
<div class="container">
  <h1>Hero: <%= @hero.name %></h1>
  <h6>Rank: <%= @hero.rank %></h6>
  <h6>History:</h6>
  <% @hero.threats.each do |threat| %>
    <p><%= threat.monstername %></p>
  <% end %>
  <%= link_to "Heros", heros_path, class: 'btn btn-primary' %>
  <%= link_to "Edit", edit_hero_path, class: 'btn btn-outline-primary' %>
</div>